/**
 * Stable identifiers for downstream analytics wiring.
 * Every CTA / form / primary link should pass one of these to data-cta.
 */
export const cta = {
  navStartSelling: 'nav-start-selling',
  navGetApp: 'nav-get-app',
  heroStartSelling: 'hero-start-selling',
  heroGetApp: 'hero-get-app',
  bandStartSelling: 'cta-band-start-selling',
  bandGetApp: 'cta-band-get-app',
  vendorFormSubmit: 'vendor-form-submit',
  contactFormSubmit: 'contact-form-submit',
  footerStartSelling: 'footer-start-selling',
  footerGetApp: 'footer-get-app',
  stickyStartSelling: 'sticky-start-selling',
  stickyGetApp: 'sticky-get-app',
  drawerStartSelling: 'drawer-start-selling',
  drawerGetApp: 'drawer-get-app',
  appStoreApple: 'appstore-apple',
  appStoreGoogle: 'appstore-google',
} as const;

export const countryCodes: { code: string; label: string }[] = [
  { code: '+1', label: '+1 · US/CA' },
  { code: '+44', label: '+44 · UK' },
  { code: '+91', label: '+91 · IN' },
  { code: '+971', label: '+971 · AE' },
  { code: '+61', label: '+61 · AU' },
  { code: '+65', label: '+65 · SG' },
  { code: '+27', label: '+27 · ZA' },
  { code: '+234', label: '+234 · NG' },
  { code: '+254', label: '+254 · KE' },
  { code: '+62', label: '+62 · ID' },
  { code: '+60', label: '+60 · MY' },
  { code: '+63', label: '+63 · PH' },
  { code: '+66', label: '+66 · TH' },
  { code: '+84', label: '+84 · VN' },
  { code: '+880', label: '+880 · BD' },
  { code: '+92', label: '+92 · PK' },
  { code: '+94', label: '+94 · LK' },
  { code: '+49', label: '+49 · DE' },
  { code: '+33', label: '+33 · FR' },
  { code: '+34', label: '+34 · ES' },
  { code: '+39', label: '+39 · IT' },
  { code: '+31', label: '+31 · NL' },
  { code: '+46', label: '+46 · SE' },
  { code: '+47', label: '+47 · NO' },
  { code: '+45', label: '+45 · DK' },
  { code: '+353', label: '+353 · IE' },
  { code: '+52', label: '+52 · MX' },
  { code: '+55', label: '+55 · BR' },
  { code: '+54', label: '+54 · AR' },
  { code: '+56', label: '+56 · CL' },
];
